name: Build Debug APK

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build_debug_apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Repository (telon-gateway-app)
        uses: actions/checkout@v4

      - name: Clone Required Libraries as Siblings
        run: |
          cd $GITHUB_WORKSPACE/..
          git clone https://github.com/horlas08/react-native-tele.git
          git clone https://github.com/horlas08/react-native-sip2.git
          git clone https://github.com/horlas08/react-native-replace-dialer.git

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 12

      - name: Install OpenJDK 8
        run: |
          sudo apt update
          sudo apt install -y openjdk-8-jdk

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 29
          build-tools: 29.0.3

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: Install Dependencies
        run: yarn install

      - name: Build Debug APK
        working-directory: android
        run: |
          chmod +x gradlew
          ./gradlew clean
          ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
